/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminSystemRouteImport } from './routes/_admin.system'
import { Route as AdminBasicRouteImport } from './routes/_admin.basic'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'
import { Route as AdminAiProvidersRouteImport } from './routes/_admin.ai-providers'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBasicRoute = AdminBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiProvidersRoute = AdminAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ai-providers': typeof AdminAiProvidersRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/basic': typeof AdminBasicRoute
  '/system': typeof AdminSystemRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ai-providers': typeof AdminAiProvidersRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/basic': typeof AdminBasicRoute
  '/system': typeof AdminSystemRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_admin/ai-providers': typeof AdminAiProvidersRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/basic': typeof AdminBasicRoute
  '/_admin/system': typeof AdminSystemRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/ai-providers'
    | '/analytics'
    | '/basic'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/unauthorized'
    | '/ai-providers'
    | '/analytics'
    | '/basic'
    | '/system'
    | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/unauthorized'
    | '/_admin/ai-providers'
    | '/_admin/analytics'
    | '/_admin/basic'
    | '/_admin/system'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/system': {
      id: '/_admin/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/basic': {
      id: '/_admin/basic'
      path: '/basic'
      fullPath: '/basic'
      preLoaderRoute: typeof AdminBasicRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-providers': {
      id: '/_admin/ai-providers'
      path: '/ai-providers'
      fullPath: '/ai-providers'
      preLoaderRoute: typeof AdminAiProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiProvidersRoute: typeof AdminAiProvidersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBasicRoute: typeof AdminBasicRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiProvidersRoute: AdminAiProvidersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBasicRoute: AdminBasicRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
