/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminSystemRouteImport } from './routes/_admin.system'
import { Route as AdminDichaAiRouteImport } from './routes/_admin.dicha-ai'
import { Route as AdminBasicRouteImport } from './routes/_admin.basic'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'
import { Route as AdminAiProvidersRouteImport } from './routes/_admin.ai-providers'
import { Route as AdminAiInvokeTestRouteImport } from './routes/_admin.ai-invoke-test'
import { Route as AdminAiDiagnosticsRouteImport } from './routes/_admin.ai-diagnostics'
import { Route as AdminCreditsRulesRouteImport } from './routes/_admin.credits.rules'
import { Route as AdminCreditsRedemptionCodesRouteImport } from './routes/_admin.credits.redemption-codes'
import { Route as AdminCreditsOperationsRouteImport } from './routes/_admin.credits.operations'
import { Route as AdminCreditsLedgerRouteImport } from './routes/_admin.credits.ledger'
import { Route as AdminCreditsGrantsRouteImport } from './routes/_admin.credits.grants'
import { Route as AdminCreditsBalancesRouteImport } from './routes/_admin.credits.balances'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDichaAiRoute = AdminDichaAiRouteImport.update({
  id: '/dicha-ai',
  path: '/dicha-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBasicRoute = AdminBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiProvidersRoute = AdminAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiInvokeTestRoute = AdminAiInvokeTestRouteImport.update({
  id: '/ai-invoke-test',
  path: '/ai-invoke-test',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiDiagnosticsRoute = AdminAiDiagnosticsRouteImport.update({
  id: '/ai-diagnostics',
  path: '/ai-diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsRulesRoute = AdminCreditsRulesRouteImport.update({
  id: '/credits/rules',
  path: '/credits/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsRedemptionCodesRoute =
  AdminCreditsRedemptionCodesRouteImport.update({
    id: '/credits/redemption-codes',
    path: '/credits/redemption-codes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCreditsOperationsRoute = AdminCreditsOperationsRouteImport.update({
  id: '/credits/operations',
  path: '/credits/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsLedgerRoute = AdminCreditsLedgerRouteImport.update({
  id: '/credits/ledger',
  path: '/credits/ledger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsGrantsRoute = AdminCreditsGrantsRouteImport.update({
  id: '/credits/grants',
  path: '/credits/grants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsBalancesRoute = AdminCreditsBalancesRouteImport.update({
  id: '/credits/balances',
  path: '/credits/balances',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/ai-invoke-test': typeof AdminAiInvokeTestRoute
  '/ai-providers': typeof AdminAiProvidersRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/basic': typeof AdminBasicRoute
  '/dicha-ai': typeof AdminDichaAiRoute
  '/system': typeof AdminSystemRoute
  '/credits/balances': typeof AdminCreditsBalancesRoute
  '/credits/grants': typeof AdminCreditsGrantsRoute
  '/credits/ledger': typeof AdminCreditsLedgerRoute
  '/credits/operations': typeof AdminCreditsOperationsRoute
  '/credits/redemption-codes': typeof AdminCreditsRedemptionCodesRoute
  '/credits/rules': typeof AdminCreditsRulesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/ai-invoke-test': typeof AdminAiInvokeTestRoute
  '/ai-providers': typeof AdminAiProvidersRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/basic': typeof AdminBasicRoute
  '/dicha-ai': typeof AdminDichaAiRoute
  '/system': typeof AdminSystemRoute
  '/': typeof AdminIndexRoute
  '/credits/balances': typeof AdminCreditsBalancesRoute
  '/credits/grants': typeof AdminCreditsGrantsRoute
  '/credits/ledger': typeof AdminCreditsLedgerRoute
  '/credits/operations': typeof AdminCreditsOperationsRoute
  '/credits/redemption-codes': typeof AdminCreditsRedemptionCodesRoute
  '/credits/rules': typeof AdminCreditsRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_admin/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/_admin/ai-invoke-test': typeof AdminAiInvokeTestRoute
  '/_admin/ai-providers': typeof AdminAiProvidersRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/basic': typeof AdminBasicRoute
  '/_admin/dicha-ai': typeof AdminDichaAiRoute
  '/_admin/system': typeof AdminSystemRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/credits/balances': typeof AdminCreditsBalancesRoute
  '/_admin/credits/grants': typeof AdminCreditsGrantsRoute
  '/_admin/credits/ledger': typeof AdminCreditsLedgerRoute
  '/_admin/credits/operations': typeof AdminCreditsOperationsRoute
  '/_admin/credits/redemption-codes': typeof AdminCreditsRedemptionCodesRoute
  '/_admin/credits/rules': typeof AdminCreditsRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/ai-diagnostics'
    | '/ai-invoke-test'
    | '/ai-providers'
    | '/analytics'
    | '/basic'
    | '/dicha-ai'
    | '/system'
    | '/credits/balances'
    | '/credits/grants'
    | '/credits/ledger'
    | '/credits/operations'
    | '/credits/redemption-codes'
    | '/credits/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/unauthorized'
    | '/ai-diagnostics'
    | '/ai-invoke-test'
    | '/ai-providers'
    | '/analytics'
    | '/basic'
    | '/dicha-ai'
    | '/system'
    | '/'
    | '/credits/balances'
    | '/credits/grants'
    | '/credits/ledger'
    | '/credits/operations'
    | '/credits/redemption-codes'
    | '/credits/rules'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/unauthorized'
    | '/_admin/ai-diagnostics'
    | '/_admin/ai-invoke-test'
    | '/_admin/ai-providers'
    | '/_admin/analytics'
    | '/_admin/basic'
    | '/_admin/dicha-ai'
    | '/_admin/system'
    | '/_admin/'
    | '/_admin/credits/balances'
    | '/_admin/credits/grants'
    | '/_admin/credits/ledger'
    | '/_admin/credits/operations'
    | '/_admin/credits/redemption-codes'
    | '/_admin/credits/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/system': {
      id: '/_admin/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dicha-ai': {
      id: '/_admin/dicha-ai'
      path: '/dicha-ai'
      fullPath: '/dicha-ai'
      preLoaderRoute: typeof AdminDichaAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/basic': {
      id: '/_admin/basic'
      path: '/basic'
      fullPath: '/basic'
      preLoaderRoute: typeof AdminBasicRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-providers': {
      id: '/_admin/ai-providers'
      path: '/ai-providers'
      fullPath: '/ai-providers'
      preLoaderRoute: typeof AdminAiProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-invoke-test': {
      id: '/_admin/ai-invoke-test'
      path: '/ai-invoke-test'
      fullPath: '/ai-invoke-test'
      preLoaderRoute: typeof AdminAiInvokeTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-diagnostics': {
      id: '/_admin/ai-diagnostics'
      path: '/ai-diagnostics'
      fullPath: '/ai-diagnostics'
      preLoaderRoute: typeof AdminAiDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/credits/rules': {
      id: '/_admin/credits/rules'
      path: '/credits/rules'
      fullPath: '/credits/rules'
      preLoaderRoute: typeof AdminCreditsRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/credits/redemption-codes': {
      id: '/_admin/credits/redemption-codes'
      path: '/credits/redemption-codes'
      fullPath: '/credits/redemption-codes'
      preLoaderRoute: typeof AdminCreditsRedemptionCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/credits/operations': {
      id: '/_admin/credits/operations'
      path: '/credits/operations'
      fullPath: '/credits/operations'
      preLoaderRoute: typeof AdminCreditsOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/credits/ledger': {
      id: '/_admin/credits/ledger'
      path: '/credits/ledger'
      fullPath: '/credits/ledger'
      preLoaderRoute: typeof AdminCreditsLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/credits/grants': {
      id: '/_admin/credits/grants'
      path: '/credits/grants'
      fullPath: '/credits/grants'
      preLoaderRoute: typeof AdminCreditsGrantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/credits/balances': {
      id: '/_admin/credits/balances'
      path: '/credits/balances'
      fullPath: '/credits/balances'
      preLoaderRoute: typeof AdminCreditsBalancesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiDiagnosticsRoute: typeof AdminAiDiagnosticsRoute
  AdminAiInvokeTestRoute: typeof AdminAiInvokeTestRoute
  AdminAiProvidersRoute: typeof AdminAiProvidersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBasicRoute: typeof AdminBasicRoute
  AdminDichaAiRoute: typeof AdminDichaAiRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCreditsBalancesRoute: typeof AdminCreditsBalancesRoute
  AdminCreditsGrantsRoute: typeof AdminCreditsGrantsRoute
  AdminCreditsLedgerRoute: typeof AdminCreditsLedgerRoute
  AdminCreditsOperationsRoute: typeof AdminCreditsOperationsRoute
  AdminCreditsRedemptionCodesRoute: typeof AdminCreditsRedemptionCodesRoute
  AdminCreditsRulesRoute: typeof AdminCreditsRulesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiDiagnosticsRoute: AdminAiDiagnosticsRoute,
  AdminAiInvokeTestRoute: AdminAiInvokeTestRoute,
  AdminAiProvidersRoute: AdminAiProvidersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBasicRoute: AdminBasicRoute,
  AdminDichaAiRoute: AdminDichaAiRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCreditsBalancesRoute: AdminCreditsBalancesRoute,
  AdminCreditsGrantsRoute: AdminCreditsGrantsRoute,
  AdminCreditsLedgerRoute: AdminCreditsLedgerRoute,
  AdminCreditsOperationsRoute: AdminCreditsOperationsRoute,
  AdminCreditsRedemptionCodesRoute: AdminCreditsRedemptionCodesRoute,
  AdminCreditsRulesRoute: AdminCreditsRulesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
