/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorldRouteImport } from './routes/_app/world'
import { Route as AppWardrobeRouteImport } from './routes/_app/wardrobe'
import { Route as AppStorageRoomRouteImport } from './routes/_app/storage-room'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppSettingsThemeRouteImport } from './routes/_app/settings.theme'
import { Route as AppSettingsStorageRouteImport } from './routes/_app/settings.storage'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings.security'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings.profile'
import { Route as AppSettingsPrivacyRouteImport } from './routes/_app/settings.privacy'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings.notifications'
import { Route as AppSettingsLanguageRouteImport } from './routes/_app/settings.language'
import { Route as AppSettingsLabsRouteImport } from './routes/_app/settings.labs'
import { Route as AppSettingsHelpRouteImport } from './routes/_app/settings.help'
import { Route as AppSettingsExportRouteImport } from './routes/_app/settings.export'
import { Route as AppSettingsDiagnosticsRouteImport } from './routes/_app/settings.diagnostics'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings.appearance'
import { Route as AppSettingsAiUsageRouteImport } from './routes/_app/settings.ai-usage'
import { Route as AppSettingsAiProvidersRouteImport } from './routes/_app/settings.ai-providers'
import { Route as AppSettingsAiModelsRouteImport } from './routes/_app/settings.ai-models'
import { Route as AppSettingsAiInvokeDemoRouteImport } from './routes/_app/settings.ai-invoke-demo'
import { Route as AppSettingsAboutRouteImport } from './routes/_app/settings.about'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorldRoute = AppWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => AppRoute,
} as any)
const AppWardrobeRoute = AppWardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => AppRoute,
} as any)
const AppStorageRoomRoute = AppStorageRoomRouteImport.update({
  id: '/storage-room',
  path: '/storage-room',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsThemeRoute = AppSettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsStorageRoute = AppSettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsLanguageRoute = AppSettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLabsRoute = AppSettingsLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsHelpRoute = AppSettingsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsExportRoute = AppSettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDiagnosticsRoute = AppSettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiUsageRoute = AppSettingsAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiProvidersRoute = AppSettingsAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiModelsRoute = AppSettingsAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiInvokeDemoRoute = AppSettingsAiInvokeDemoRouteImport.update({
  id: '/ai-invoke-demo',
  path: '/ai-invoke-demo',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/home': typeof AppHomeRoute
  '/library': typeof AppLibraryRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/storage-room': typeof AppStorageRoomRoute
  '/wardrobe': typeof AppWardrobeRoute
  '/world': typeof AppWorldRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/ai-invoke-demo': typeof AppSettingsAiInvokeDemoRoute
  '/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/settings/ai-providers': typeof AppSettingsAiProvidersRoute
  '/settings/ai-usage': typeof AppSettingsAiUsageRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/settings/export': typeof AppSettingsExportRoute
  '/settings/help': typeof AppSettingsHelpRoute
  '/settings/labs': typeof AppSettingsLabsRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/storage': typeof AppSettingsStorageRoute
  '/settings/theme': typeof AppSettingsThemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/home': typeof AppHomeRoute
  '/library': typeof AppLibraryRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/storage-room': typeof AppStorageRoomRoute
  '/wardrobe': typeof AppWardrobeRoute
  '/world': typeof AppWorldRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/ai-invoke-demo': typeof AppSettingsAiInvokeDemoRoute
  '/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/settings/ai-providers': typeof AppSettingsAiProvidersRoute
  '/settings/ai-usage': typeof AppSettingsAiUsageRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/settings/export': typeof AppSettingsExportRoute
  '/settings/help': typeof AppSettingsHelpRoute
  '/settings/labs': typeof AppSettingsLabsRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/storage': typeof AppSettingsStorageRoute
  '/settings/theme': typeof AppSettingsThemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/storage-room': typeof AppStorageRoomRoute
  '/_app/wardrobe': typeof AppWardrobeRoute
  '/_app/world': typeof AppWorldRoute
  '/_app/settings/about': typeof AppSettingsAboutRoute
  '/_app/settings/ai-invoke-demo': typeof AppSettingsAiInvokeDemoRoute
  '/_app/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/_app/settings/ai-providers': typeof AppSettingsAiProvidersRoute
  '/_app/settings/ai-usage': typeof AppSettingsAiUsageRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/_app/settings/export': typeof AppSettingsExportRoute
  '/_app/settings/help': typeof AppSettingsHelpRoute
  '/_app/settings/labs': typeof AppSettingsLabsRoute
  '/_app/settings/language': typeof AppSettingsLanguageRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/storage': typeof AppSettingsStorageRoute
  '/_app/settings/theme': typeof AppSettingsThemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/home'
    | '/library'
    | '/settings'
    | '/storage-room'
    | '/wardrobe'
    | '/world'
    | '/settings/about'
    | '/settings/ai-invoke-demo'
    | '/settings/ai-models'
    | '/settings/ai-providers'
    | '/settings/ai-usage'
    | '/settings/appearance'
    | '/settings/diagnostics'
    | '/settings/export'
    | '/settings/help'
    | '/settings/labs'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/storage'
    | '/settings/theme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/home'
    | '/library'
    | '/settings'
    | '/storage-room'
    | '/wardrobe'
    | '/world'
    | '/settings/about'
    | '/settings/ai-invoke-demo'
    | '/settings/ai-models'
    | '/settings/ai-providers'
    | '/settings/ai-usage'
    | '/settings/appearance'
    | '/settings/diagnostics'
    | '/settings/export'
    | '/settings/help'
    | '/settings/labs'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/storage'
    | '/settings/theme'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/account'
    | '/_app/home'
    | '/_app/library'
    | '/_app/settings'
    | '/_app/storage-room'
    | '/_app/wardrobe'
    | '/_app/world'
    | '/_app/settings/about'
    | '/_app/settings/ai-invoke-demo'
    | '/_app/settings/ai-models'
    | '/_app/settings/ai-providers'
    | '/_app/settings/ai-usage'
    | '/_app/settings/appearance'
    | '/_app/settings/diagnostics'
    | '/_app/settings/export'
    | '/_app/settings/help'
    | '/_app/settings/labs'
    | '/_app/settings/language'
    | '/_app/settings/notifications'
    | '/_app/settings/privacy'
    | '/_app/settings/profile'
    | '/_app/settings/security'
    | '/_app/settings/storage'
    | '/_app/settings/theme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/world': {
      id: '/_app/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof AppWorldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wardrobe': {
      id: '/_app/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof AppWardrobeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storage-room': {
      id: '/_app/storage-room'
      path: '/storage-room'
      fullPath: '/storage-room'
      preLoaderRoute: typeof AppStorageRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/theme': {
      id: '/_app/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof AppSettingsThemeRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/storage': {
      id: '/_app/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof AppSettingsStorageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/privacy': {
      id: '/_app/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/language': {
      id: '/_app/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AppSettingsLanguageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/labs': {
      id: '/_app/settings/labs'
      path: '/labs'
      fullPath: '/settings/labs'
      preLoaderRoute: typeof AppSettingsLabsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/help': {
      id: '/_app/settings/help'
      path: '/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof AppSettingsHelpRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/export': {
      id: '/_app/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof AppSettingsExportRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/diagnostics': {
      id: '/_app/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof AppSettingsDiagnosticsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai-usage': {
      id: '/_app/settings/ai-usage'
      path: '/ai-usage'
      fullPath: '/settings/ai-usage'
      preLoaderRoute: typeof AppSettingsAiUsageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai-providers': {
      id: '/_app/settings/ai-providers'
      path: '/ai-providers'
      fullPath: '/settings/ai-providers'
      preLoaderRoute: typeof AppSettingsAiProvidersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai-models': {
      id: '/_app/settings/ai-models'
      path: '/ai-models'
      fullPath: '/settings/ai-models'
      preLoaderRoute: typeof AppSettingsAiModelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai-invoke-demo': {
      id: '/_app/settings/ai-invoke-demo'
      path: '/ai-invoke-demo'
      fullPath: '/settings/ai-invoke-demo'
      preLoaderRoute: typeof AppSettingsAiInvokeDemoRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/about': {
      id: '/_app/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAiInvokeDemoRoute: typeof AppSettingsAiInvokeDemoRoute
  AppSettingsAiModelsRoute: typeof AppSettingsAiModelsRoute
  AppSettingsAiProvidersRoute: typeof AppSettingsAiProvidersRoute
  AppSettingsAiUsageRoute: typeof AppSettingsAiUsageRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsDiagnosticsRoute: typeof AppSettingsDiagnosticsRoute
  AppSettingsExportRoute: typeof AppSettingsExportRoute
  AppSettingsHelpRoute: typeof AppSettingsHelpRoute
  AppSettingsLabsRoute: typeof AppSettingsLabsRoute
  AppSettingsLanguageRoute: typeof AppSettingsLanguageRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsStorageRoute: typeof AppSettingsStorageRoute
  AppSettingsThemeRoute: typeof AppSettingsThemeRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAiInvokeDemoRoute: AppSettingsAiInvokeDemoRoute,
  AppSettingsAiModelsRoute: AppSettingsAiModelsRoute,
  AppSettingsAiProvidersRoute: AppSettingsAiProvidersRoute,
  AppSettingsAiUsageRoute: AppSettingsAiUsageRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsDiagnosticsRoute: AppSettingsDiagnosticsRoute,
  AppSettingsExportRoute: AppSettingsExportRoute,
  AppSettingsHelpRoute: AppSettingsHelpRoute,
  AppSettingsLabsRoute: AppSettingsLabsRoute,
  AppSettingsLanguageRoute: AppSettingsLanguageRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsStorageRoute: AppSettingsStorageRoute,
  AppSettingsThemeRoute: AppSettingsThemeRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppStorageRoomRoute: typeof AppStorageRoomRoute
  AppWardrobeRoute: typeof AppWardrobeRoute
  AppWorldRoute: typeof AppWorldRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppHomeRoute: AppHomeRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppStorageRoomRoute: AppStorageRoomRoute,
  AppWardrobeRoute: AppWardrobeRoute,
  AppWorldRoute: AppWorldRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
